# Generated by Django 5.0.7 on 2024-07-23 08:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("org", "0003_userprofile_delete_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
