# Generated by Django 5.0.7 on 2024-07-25 08:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("org", "0008_team_users"),
    ]

    operations = [
        migrations.DeleteModel(
            name="File",
        ),
    ]
